apiVersion: v1
kind: ResourceQuota
metadata:
  name: vuln-lab-quota
  namespace: vuln-lab
spec:
  hard:
    requests.cpu: "6"
    limits.cpu: "8"
    requests.memory: 4Gi
    limits.memory: 6Gi
    pods: "20"
    services: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: vuln-lab-limits
  namespace: vuln-lab
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: "1"
        memory: 1536Mi
      max:
        cpu: "2"
        memory: 2Gi
      min:
        cpu: 50m
        memory: 64Mi
