apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vuln-lab

resources:
  - 00-namespace.yaml
  - 01-resource-quota.yaml
  - 02-rbac.yaml
  - 20-networkpolicy-egress-dns-only.yaml
  - 21-networkpolicy-ingress-nginx-only.yaml
  - 30-deployments-services.yaml
  - 40-ingress.yaml
