apiVersion: apps/v1
kind: Deployment
metadata:
  name: "task-{{UUID}}"
  namespace: vuln-lab
  labels:
    app.kubernetes.io/name: "task-{{UUID}}"
    app.kubernetes.io/part-of: vuln-lab # Активирует NetworkPolicies (20 и 21)
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "task-{{UUID}}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "task-{{UUID}}"
        app.kubernetes.io/part-of: vuln-lab
    spec:
      serviceAccountName: "sa-{{UUID}}"
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: "{{IMAGE}}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{PORT}}
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL