apiVersion: v1
kind: Service
metadata:
  name: "task-{{UUID}}"
  namespace: vuln-lab
  labels:
    app.kubernetes.io/name: "task-{{UUID}}"
    app.kubernetes.io/part-of: vuln-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "task-{{UUID}}"
  ports:
    - name: http
      port: 80
      targetPort: http